# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# blah
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "ad:49:16:76:02:2a:f4:23:03:e7:8b:0c:0d:a6:e1:91"

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: ssh-keyscan -H mwilber.com >> ~/.ssh/known_hosts
      - run: npm run build
      - run: scp -r dist/* greenzeta@mwilber.com:/home/greenzeta/staging.greenzeta.com/zetaburger/
workflows:
  version: 2
  build_xen:
    jobs:
      - build:
          filters:
            branches:
              only: master